import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { AppHeader } from "@/components/AppHeader";
import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <div className="min-h-screen flex flex-col items-center">
          <AppHeader />
          <main className="flex-1 flex flex-col items-center justify-center w-full pt-20 bg-zinc-50">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
